#!/bin/bash

set -o errexit

# Set up local variables and export GIT_WORK_TREE because it
# gets used
GITROOT=/home/willkg/projects/blog.git

# Add ~/.local/bin to path because that's where just and uv are
export PATH=$PATH:/home/willkg/.local/bin

echo ">>> checking out main"
cd ..
env -i git reset --hard

# unset GIT_INDEX_FILE

# unset GIT_DIR so that pip works right with git-based requirements
unset GIT_DIR

# Create logs directory if needed
if [[ ! -d ./logs/ ]]
then
    echo ">>> logs directory doesn't exist; creating"
    mkdir ./logs/
fi

# Update venv if needed
echo ">>> create devenv"
echo ">>> create devenv" > build.log
just devenv >> build.log

# Compile the blog, time it and generate logs.
echo ">>> compile"
echo ">>> compile" >> build.log
time ./compile.sh >> ./logs/build.log
